facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    root: 
    org.springframework.security: DEBUG
    
spring:
    application:
        name: cruncher
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring
        username: root
        password: naveen
    jpa:
      database: MYSQL
      hibernate:
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      
server:
    port: 8080
    context-path: /demo
    display-name: Demo
    
debug: false
